FROM python:3.9-alpine3.18

WORKDIR /app

RUN apk add curl

RUN python -m pip install --upgrade pip

ENV XDG_CONFIG_HOME=/var

RUN cd /tmp && \
    curl -sSL https://install.python-poetry.org > get-poetry.py && \
    POETRY_HOME=/opt/poetry python get-poetry.py --version 1.8.2 && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false
COPY pyproject.toml /tmp/
COPY poetry.lock /tmp/
RUN cd /tmp && poetry install --no-root --no-dev

COPY ./pyproject.toml /tmp/

COPY ./poetry.lock /tmp/

RUN cd /tmp && poetry install --no-root --no-dev

COPY ./mock /app/src
COPY ./pyproject.toml /app

EXPOSE 8000

ENV PROMETHEUS_MULTIPROC_DIR=/tmp
ENV PY_ENV=local

ENTRYPOINT ["poetry", "run"]
CMD ["python", "src/main.py"]
